# Generated by Django 5.1.3 on 2025-01-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.JSONField()),
                ('feedback_image', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='core.preprocessedimage')),
            ],
        ),
    ]
