# Generated by Django 5.1.3 on 2025-01-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedbackimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='preprocessed_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preprocessedimage'),
        ),
    ]
