# Generated by Django 5.1.3 on 2025-01-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_feedbackimage_feedback_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='analyzed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_images', to='core.analyzedimage'),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='preprocessed_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_images', to='core.preprocessedimage'),
        ),
    ]
