# Generated by Django 5.1.3 on 2025-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_logentry_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='comparison_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
