# Generated by Django 5.1.3 on 2025-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedbackimage_review_notes_feedbackimage_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessedimage',
            name='image',
            field=models.ImageField(upload_to='preprocessed_images/'),
        ),
    ]
