# Generated by Django 5.1.3 on 2025-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedbackimage_review_notes_feedbackimage_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='minio_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='minio_object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='minio_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='minio_object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
