# Generated by Django 5.1.3 on 2025-04-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_preprocessedimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackimage',
            name='minio_bucket',
        ),
        migrations.RemoveField(
            model_name='feedbackimage',
            name='minio_object_name',
        ),
    ]
