# Generated by Django 5.1.3 on 2025-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_preprocessedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='bucket_name',
            field=models.CharField(default='skinimages', max_length=100),
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
