# Generated by Django 5.1.3 on 2025-04-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_feedbackimage_minio_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='preprocessed_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_image', to='core.preprocessedimage'),
        ),
    ]
