# Generated by Django 5.1.3 on 2025-05-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_feedbackimage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstReviewerFeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.JSONField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('feedback_given_at', models.DateTimeField(auto_now_add=True)),
                ('retrained', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed')], default='reviewed', max_length=20)),
                ('analyzed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_reviewer_feedback_images', to='core.analyzedimage')),
                ('preprocessed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_reviewer_feedback_images', to='core.preprocessedimage')),
            ],
        ),
    ]
