# Generated by Django 5.1.3 on 2025-04-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_analyzedimage_preprocessed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='minio_bucket',
        ),
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='minio_object_name',
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='preprocessed_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_image', to='core.preprocessedimage'),
        ),
    ]
