# Generated by Django 5.1.3 on 2025-04-26 12:50

from django.db import migrations

def remove_duplicate_analyzed_images(apps, schema_editor):
    AnalyzedImage = apps.get_model('core', 'AnalyzedImage')
    # We're deleting the older record with ID 151
    AnalyzedImage.objects.filter(id=151).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_preprocessedimage_minio_bucket_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_analyzed_images),
    ]
