version: '3.8'

services:
  backend:
    build:
      context: ./backend_project
      dockerfile: dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend_project:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - db
      - ai_models

  ai_models:
    build:
      context: ./backend_project/apps/ai_models
      dockerfile: Dockerfile
    container_name: ai-models
    ports:
      - "8001:8001"
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zwamtestar3
      POSTGRES_DB: AI_skincancer_detection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow_data:/mlflow
    command:
      - mlflow
      - server
      - --backend-store-uri
      - sqlite:///mlflow.db
      - --default-artifact-root
      - /mlflow/artifacts
      - --host
      - 0.0.0.0
      - --port
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  mlflow_data: