version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always
    networks:
      - app_network

  celery:
    build:
      context: .
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    networks:
      - app_network

networks:
  app_network:

volumes:
  redis_data:
