# Generated by Django 5.1.3 on 2025-01-09 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_feedbackimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackimage',
            name='feedback_image',
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='feedback_given_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='preprocessed_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='core.preprocessedimage'),
        ),
    ]
