# Generated by Django 5.1.3 on 2025-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedbackimage_analyzed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='retrained',
            field=models.BooleanField(default=False),
        ),
    ]
