# Generated by Django 5.1.3 on 2025-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
