# Generated by Django 5.1.3 on 2024-12-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprocessedimage',
            old_name='image_data',
            new_name='image',
        ),
    ]
