# Generated by Django 5.1.3 on 2024-12-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_rename_image_data_preprocessedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedimage',
            name='processed_at',
        ),
    ]
