# Generated by Django 5.1.3 on 2024-12-05 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_remove_preprocessedimage_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessedimage',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
