# Generated by Django 5.1.3 on 2024-12-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0004_preprocessedimage_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.preprocessedimage')),
            ],
        ),
    ]
