# Generated by Django 5.1.3 on 2024-12-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0005_analyzedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzedImage',
        ),
    ]
