# Generated by Django 5.1.3 on 2024-12-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocessing', '0004_preprocessedimage_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_results', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_image', to='preprocessing.preprocessedimage')),
            ],
        ),
    ]
